# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# получение всех пользователей

GET http://golf.rarus-crimea.ru/api/users/
Content-Type: application/json
Authorization: Basic bWFzdGVyOm1hc3RlcjEyMw==

###

# получение пользователя по id

GET http://golf.rarus-crimea.ru/api/users/1
Content-Type: application/json
Authorization: Basic bWFzdGVyOm1hc3RlcjEyMw==

###

# создание пользователя
POST http://golf.rarus-crimea.ru/api/users/create
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic bWFzdGVyOm1hc3RlcjEyMw==

--WebAppBoundary
Content-Disposition: form-data; name="login"

Holly
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="password"

Molly
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="position"

manager
--WebAppBoundary--

###

# редактирование пользователя
POST http://golf.rarus-crimea.ru/api/users/update
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic bWFzdGVyOm1hc3RlcjEyMw==

--WebAppBoundary
Content-Disposition: form-data; name="id"

22
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="password"

Tolly
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="position"

Nigga
--WebAppBoundary--

###

# удаление пользователя
POST http://golf.rarus-crimea.ru/api/users/delete
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic bWFzdGVyOm1hc3RlcjEyMw==

--WebAppBoundary
Content-Disposition: form-data; name="login"

Holly
--WebAppBoundary--

###